version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:us-east-1:111271881861:task-definition/Product-service-td:2"
        LoadBalancerInfo:
          ContainerName: "productservice"
          ContainerPort: "8083"
        PlatformVersion: "LATEST"
